### ISSUE TITLE
Switch from Local Sqlite DB to Remote Postgres DB

### ISSUE THREAD

**Issue by edrouth** [app-generator/api-server-nodejs#14]

**Comment by app-generator** [comment]
Hello @edrouth 

Thank you for using our products. Please provide more context, if possible: 

- Nodejs version
- Runtime error log (text format) 
- Other things you consider to be important 
- Also, clarify the meaning of the `remote`  
  - with a local version the app works?
  - PostgreSQL client drivers are installed
  - Are you able to connect to the remote DB using any PostgreSQL tool?

The above information helps us to reproduce faster the issue.  

Thank you!

**Comment by edrouth** [comment]
Hi team, 

Let me answer each in turn. 

- Node JS Version: v16.18.0
- Attached "localhost-1666801265109.log"
- I am able to establish connection to database through backend, the error comes when loading a page with data
- Remote I mean connect to AWS RDS database. 
- Installed pg package
- Yes, I can connect to DB via TablePlus

Thanks!
[localhost-1666801265109.log](https://github.com/app-generator/api-server-nodejs/files/9871411/localhost-1666801265109.log)
![Screenshot 2022-10-26 at 9 19 13 AM](https://user-images.githubusercontent.com/44217823/198081095-4ba37440-2ce1-4dc6-b54f-defdd7bd7a4a.png)

**Comment by app-generator** [comment]
Hello @edrouth 

After a quick look at your log, the problem seems to be in React, `<DataTable> component` 

Our advice is to analyze the problem like this: 

- test the API and visualize the data returned  
  - using POSTMAN or any other 3rd party tool
 - Use the simple JS code in React to visualize the backend data
 - The last step is to inject the data in your component

Let us know if our assumptions are correct and also your progress. 

Adrian - [AppSeed](https://appseed.us/) Support

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
